export const variableColors = {
	bg: {
		primary: {
			darkest: `var(--bg-primary-darkest)`,
			dark: `var(--bg-primary-dark)`,
			DEFAULT: ` var(--bg-primary)`,
			light: `var(--bg-primary-light)`,
			lightest: `var(--bg-primary-lightest)`,
		},
		embellish: {
			darkest: `var(--bg-embellish-darkest)`,
			dark: 'var(--bg-embellish-dark)',
			DEFAULT: 'var(--bg-embellish)',
			light: 'var(--bg-embellish-light)',
			lightest: `var(--bg-embellish-lightest)`,
		},
		striking: {
			darkest: `var(--bg-striking-darkest)`,
			dark: 'var(--bg-striking-dark)',
			DEFAULT: 'var(--bg-striking)',
			light: 'var(--bg-striking-light)',
			lightest: `var(--bg-striking-lightest)`,
		},
		white: {
			darkest: `var(--bg-white-darkest)`,
			dark: 'var(--bg-white-dark)',
			DEFAULT: 'var(--bg-white)',
			light: 'var(--bg-white-light)',
			lightest: `var(--bg-white-lightest)`,
		},
		gray: {
			darkest: `var(--bg-gray-darkest)`,
			dark: 'var(--bg-gray-dark)',
			DEFAULT: 'var(--bg-gray)',
			light: 'var(--bg-gray-light)',
			lightest: `var(--bg-gray-lightest)`,
		},
	},
	text: {
		primary: {
			darkest: `var(--text-primary-darkest)`,
			dark: `var(--text-primary-dark)`,
			DEFAULT: `var(--text-primary)`,
			light: `var(--text-primary-light)`,
			lightest: `var(--text-primary-lightest)`,
		},
		embellish: {
			darkest: `var(--text-embellish-darkest)`,
			dark: 'var(--text-embellish-dark)',
			DEFAULT: 'var(--text-embellish)',
			light: 'var(--text-embellish-light)',
			lightest: `var(--text-embellish-lightest)`,
		},
		striking: {
			darkest: `var(--text-striking-darkest)`,
			dark: 'var(--text-striking-dark)',
			DEFAULT: 'var(--text-striking)',
			light: 'var(--text-striking-light)',
			lightest: `var(--text-striking-lightest)`,
		},
		white: {
			darkest: `var(--text-white-darkest)`,
			dark: 'var(--text-white-dark)',
			DEFAULT: 'var(--text-white)',
			light: 'var(--text-white-light)',
			lightest: `var(--text-white-lightest)`,
		},
		gray: {
			darkest: `var(--text-gray-darkest)`,
			dark: 'var(--text-gray-dark)',
			DEFAULT: 'var(--text-gray)',
			light: 'var(--text-gray-light)',
			lightest: `var(--text-gray-lightest)`,
		},
	},
	common: {
		inherit: 'inherit',
		current: 'currentColor',
		transparent: 'transparent',
	},
};
